version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/nginx-proxy-manager/data:/data
      - /portainer/Files/AppData/Config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - stats
    ports:
      - 80:80
      - 443:443
      - 81:81

  stats:
    image: justsky/goaccess-for-nginxproxymanager:latest
    container_name: nginx-stats
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/nginx-proxy-manager/data/logs:/opt/log:ro
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      BASIC_AUTH: "${BASIC_AUTH}"
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    ports:
      - 7880:7880
